c_compiler_version:        # [linux or osx]
  - 7.5.0                  # [linux and not (s390x or aarch64 or ppc64le)]
  - 7.3.0                  # [linux and ppc64le]
  - 7.5.0                  # [linux and s390x]
  - 10.2.0                 # [linux and aarch64]
  - 12                     # [osx]