{% set name = "openssl" %}
{% set version = "1.0.2t" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.openssl.org/source/{{ name }}-{{ version }}.tar.gz
  sha256: 14cb464efe7ac6b54799b34456bd69558a749a4931ecfd9cf9f71d7881cac7bc
  patches:
    - openssl-1.0.2d-parallel-build.patch

build:
  number: 0
  no_link: lib/libcrypto.so.1.0.0      # [linux]
  no_link: lib/libcrypto.1.0.0.dylib     # [osx]
  has_prefix_files:                      # [unix]
    - bin/c_rehash                       # [unix]
    - include/openssl/opensslconf.h      # [unix]
    - lib/pkgconfig/libcrypto.pc         # [unix]
    - lib/pkgconfig/libssl.pc            # [unix]
    - lib/pkgconfig/openssl.pc           # [unix]
  features:
     - vc{{ vc }}     # [win]
  run_exports:
    # openssl's versioning is X.Y.Z(rev), where rev is really the patch release ID
    #    This pin allows the patch release to be >= the build-time openssl version.
    - {{ pin_subpackage('openssl', max_pin='x.x.x') }}
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('c') }}
    - yasm               # [win32]
    - perl
    - make               # [unix]
    - patch              # [unix]
    - m2-patch           # [win]

  host:
    # technically a build tool, but the windows makefile really wants to find it in the host env.
    #    easier to do this than carry a patch.
    - perl
  run:
    - ca-certificates

test:
  commands:
    - copy NUL checksum.txt        # [win]
    - touch checksum.txt           # [unix]
    - openssl sha256 checksum.txt

about:
  home: http://www.openssl.org/
  license_file: LICENSE
  license: OpenSSL
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man1.1.1/

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
    - carlodri
